### ISSUE TITLE
Tor unrecognized service

### ISSUE THREAD

**Issue by gold10star** [tamilspyboysofficial/Pollscammer#3]
Getting this error which running Pollscammer.py

```
tor: unrecognized service
tor: unrecognized service
Traceback (most recent call last):
  File "/content/drive/Colab Notebooks/Pollscammer.py", line 71, in <module>
    code_statement(user_input, count)
  File "/content/drive/Colab Notebooks/Pollscammer.py", line 50, in code_statement
    user_input = subprocess.check_output("torsocks " + user_input_first, shell=True, stderr=subprocess.DEVNULL)
  File "/usr/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'torsocks https://www.polltab.com/' returned non-zero exit status 127.
```

**Comment by bashaasun** [comment]
@gold10star Did you execute install.sh 

This installs tor module required for python.
